apiVersion: v1
kind: Service
metadata:
  name: pocket-id
  namespace: pocketid
spec:
  selector:
    app: pocket-id
  ports:
    - protocol: TCP
      port: 1411
      targetPort: 1411
  type: ClusterIP
